### ISSUE TITLE
大佬咋弄的cfg解锁

### ISSUE THREAD

**Issue by w58296** [839891627/Lenovo_RUI7000_Hackintosh#10]
官网的bios解压没有fd文件_(:3」∠❀)_

**Comment by 839891627** [comment]
你是同款机型吗？ 是的话，不用自己找了，我介绍里面说了位置是多少呀

**Comment by w58296** [comment]
> 你是同款机型吗？ 是的话，不用自己找了，我介绍里面说了位置是多少呀

是同款，好的我试试。

**Comment by w58296** [comment]
> 你是同款机型吗？ 是的话，不用自己找了，我介绍里面说了位置是多少呀

再问个比较傻的问题，我可以直接用你的oc引导吗，还是说需要修改，同时我没有博通的网卡，目前我删除了博通驱动进不去安装界面，卡在苹果logo就不动了，也没有进度条

**Comment by Recxm** [comment]
> > 你是同款机型吗？ 是的话，不用自己找了，我介绍里面说了位置是多少呀
> 
> 再问个比较傻的问题，我可以直接用你的oc引导吗，还是说需要修改，同时我没有博通的网卡，目前我删除了博通驱动进不去安装界面，卡在苹果logo就不动了，也没有进度条

作者的引导文件我记得是不能直接用来安装的，需要把HFSPlus这个driver换成VBoxHFS，安装完再把HFSPlus换回去。
这个配置需要解锁CFG和调整DVMT，不然也是卡logo的，

**Comment by w58296** [comment]
> > > 你是同款机型吗？ 是的话，不用自己找了，我介绍里面说了位置是多少呀
> > 
> > 
> > 再问个比较傻的问题，我可以直接用你的oc引导吗，还是说需要修改，同时我没有博通的网卡，目前我删除了博通驱动进不去安装界面，卡在苹果logo就不动了，也没有进度条
> 
> 作者的引导文件我记得是不能直接用来安装的，需要把HFSPlus这个driver换成VBoxHFS，安装完再把HFSPlus换回去。
> 这个配置需要解锁CFG和调整DVMT，不然也是卡logo的，

cfg我解锁了，不知道dvmt需要怎么设置，设置成多少

**Comment by Recxm** [comment]
> cfg我解锁了，不知道dvmt需要怎么设置，设置成多少

链接里远景的那个文章里写的很详细的了，dvmt的值是0x2,偏移量是0xDF

**Comment by w58296** [comment]
> > cfg我解锁了，不知道dvmt需要怎么设置，设置成多少
> 
> 链接里远景的那个文章里写的很详细的了，dvmt的值是0x2,偏移量是0xDF

改完了还是卡logo，还有如果换成vbox，oc引导会报找不到hfsp，难道我下的版本不对？

**Comment by Recxm** [comment]
> 改完了还是卡logo，还有如果换成vbox，oc引导会报找不到hfsp，难道我下的版本不对？

你换了那个vbox的driver，config.plist里的配置也得跟着一起修改才行。

**Comment by 839891627** [comment]
> > > 你是同款机型吗？ 是的话，不用自己找了，我介绍里面说了位置是多少呀
> > 
> > 
> > 再问个比较傻的问题，我可以直接用你的oc引导吗，还是说需要修改，同时我没有博通的网卡，目前我删除了博通驱动进不去安装界面，卡在苹果logo就不动了，也没有进度条
> 
> 作者的引导文件我记得是不能直接用来安装的，需要把HFSPlus这个driver换成VBoxHFS，安装完再把HFSPlus换回去。
> 这个配置需要解锁CFG和调整DVMT，不然也是卡logo的，

好久没重装了，我也有点记不清楚了😂   如果实在装不成功，用这个兄弟的试试 https://github.com/Erf172/Lenovo_XiaoXin_Rui7000_Hackintosh

**Comment by w58296** [comment]
> > 改完了还是卡logo，还有如果换成vbox，oc引导会报找不到hfsp，难道我下的版本不对？
> 
> 你换了那个vbox的driver，config.plist里的配置也得跟着一起修改才行。

改了目前还是卡logo,难道是加载慢吗，但是没进度条

**Comment by w58296** [comment]
> > > > 你是同款机型吗？ 是的话，不用自己找了，我介绍里面说了位置是多少呀
> > > 
> > > 
> > > 再问个比较傻的问题，我可以直接用你的oc引导吗，还是说需要修改，同时我没有博通的网卡，目前我删除了博通驱动进不去安装界面，卡在苹果logo就不动了，也没有进度条
> > 
> > 
> > 作者的引导文件我记得是不能直接用来安装的，需要把HFSPlus这个driver换成VBoxHFS，安装完再把HFSPlus换回去。
> > 这个配置需要解锁CFG和调整DVMT，不然也是卡logo的，
> 
> 好久没重装了，我也有点记不清楚了😂 如果实在装不成功，用这个兄弟的试试 https://github.com/Erf172/Lenovo_XiaoXin_Rui7000_Hackintosh

这个兄弟的貌似只更新到15,我们俩的配置最接近，除了我少了博通的网卡，或者老哥给个big sur 镜像链接？

**Comment by 839891627** [comment]
这个仓库下载：https://github.com/corpnewt/gibMacOS
或者论坛汉化版的：http://bbs.pcbeta.com/viewthread-1867928-1-1.html

**Comment by 839891627** [comment]
安装的时候，把 -v 模式打开，这样能看到报错信息。 不然卡 logo，你看不到错误信息
![image](https://user-images.githubusercontent.com/10300651/103076521-e0cac580-4608-11eb-8c24-9895002397fd.png)

**Comment by w58296** [comment]
> 安装的时候，把 -v 模式打开，这样能看到报错信息。 不然卡 logo，你看不到错误信息
> ![image](https://user-images.githubusercontent.com/10300651/103076521-e0cac580-4608-11eb-8c24-9895002397fd.png)

目前安装都进不去

**Comment by w58296** [comment]
> > 安装的时候，把 -v 模式打开，这样能看到报错信息。 不然卡 logo，你看不到错误信息
> > ![image](https://user-images.githubusercontent.com/10300651/103076521-e0cac580-4608-11eb-8c24-9895002397fd.png)
> 
> 我试试

**Comment by Recxm** [comment]
> 这个兄弟的貌似只更新到15,我们俩的配置最接近，除了我少了博通的网卡，或者老哥给个big sur 镜像链接？

说实话，big sur体验一下就好了，不是给x86设计的，很多他那个系统的特性和性能发挥不出来，我目前是15.7拿来日常使用的。也不怎么打算折腾11的了，要用arm架构的mac系统还是等以后有钱直接换mac吧，😂

**Comment by w58296** [comment]
> 安装的时候，把 -v 模式打开，这样能看到报错信息。 不然卡 logo，你看不到错误信息
> ![image](https://user-images.githubusercontent.com/10300651/103076521-e0cac580-4608-11eb-8c24-9895002397fd.png)

老哥可以给个网卡的淘宝链接吗
