### ISSUE TITLE
作者您好！CFG已解锁，DVMT没有修改，卡在了这个界面。

### ISSUE THREAD

**Issue by Car1osLau** [839891627/Lenovo_RUI7000_Hackintosh#11]
CFG按照位置在CPUSetup确定已经解锁，更换了不同的bigsur包，通过U盘引导安装，每次都会卡在这个界面。
黑果小兵针对这串代码在config.plist改Applecfglock这些参数的建议也已经尝试。
我的锐7000直接在固态只安装了@erf172的Clover以及10.15。

请求作者大大予以解答，万分感谢！
![IMG_2044](https://user-images.githubusercontent.com/61149961/103340317-b53f5380-4abe-11eb-8c22-9be37bc74fe7.JPG)

**Comment by 839891627** [comment]
去这篇文档找找看有没有哈  https://shuiyunxc.gitee.io/2020/04/06/Faults/index/

我这个解决问题不管用 🤣

**Comment by Car1osLau** [comment]
好的好的！新年快乐XD
