### ISSUE TITLE
这个EFI是无法直接使用的，直接使用会卡loge

### ISSUE THREAD

**Issue by Freaty** [839891627/Lenovo_RUI7000_Hackintosh#12]
想直接使用EFI的同学建议移步https://github.com/Erf172/Lenovo_XiaoXin_Rui7000_Hackintosh/releases
亲测可用，i5版本的也可以。

**Comment by 839891627** [comment]
我的硬件调整过
1. 用的 sata ssd
2. 换了 无线网卡
然后 cfg 是解锁了。

配置是很精简的，所以难免有些不适配。追求完美极致的可以参考吧
