### ISSUE TITLE
HDMI不能用可以尝试下这个大佬的EFI，我的就好使了

### ISSUE THREAD

**Issue by RebornL1** [839891627/Lenovo_RUI7000_Hackintosh#2]
https://github.com/Erf172/Lenovo_XiaoXin_Rui7000_Hackintosh

**Comment by 839891627** [comment]
嗯。感谢。
这个仓库之前我看过，主要我有点洁癖，我的 config 文件很精简，都是自己一步步调出来的

然后他这个，我看过，也尝试拿一些过来用，还没尝试成功。。
而且现在黑果放在家，只用来打 lol... 办公用的公司白果，就没有再折腾了 哈哈哈
