### ISSUE TITLE
CFG、DVMT那些位置是怎么获取到

### ISSUE THREAD

**Issue by Recxm** [839891627/Lenovo_RUI7000_Hackintosh#5]
我想问下CFG和DVMT这两个的位置是怎么获取到的，我看网上的方法但是没有找到这个电脑的BIOS固件。

**Comment by 839891627** [comment]
好早之前的，快忘记了。

bios 的文件好像是 联想官网下载的https://newsupport.lenovo.com.cn/driveList.html?fromsource=driveList&selname=%E5%B0%8F%E6%96%B0%20%E9%94%907000 ，然后 远景那个教程里面， 解包bios的文件，和帖子里那个工具不一样，要自己百度下。

你要是和我一样的型号，直接用 我图里面那个位置就好了呀
