### ISSUE TITLE
使用哪个RU.efi版本？

### ISSUE THREAD

**Issue by xwwwb** [839891627/Lenovo_RUI7000_Hackintosh#6]
您好，请问，你用的是哪个版本的RU.efi，我这里进入RU.efi之后就卡死了，然后重启后无法开机
要CMOS电池放电才能开机。

**Comment by 839891627** [comment]
cfg 解锁的那个吗？ 比较久远了，记不清楚了。。 多试试吧

我之前是 clover 时候，然后解锁的

**Comment by xwwwb** [comment]
谢谢你，我找到了，我用5.21.0344这个可以用。谢谢您
