### ISSUE TITLE
大佬，我用你的配置文件替换之前的clover文件，启动就苹果图标一直卡在那边

### ISSUE THREAD

**Issue by aiwu12** [839891627/Lenovo_RUI7000_Hackintosh#7]
已经解锁cfg了，是什么原因呢

**Comment by 839891627** [comment]
-v模式开启后，看看报错信息是什么
![image](https://user-images.githubusercontent.com/10300651/100193510-e4e2c500-2f2e-11eb-947b-e8129cfa3e19.png)

**Comment by aiwu12** [comment]
![Uploading 4FF1D67A-181F-432C-A08F-122E75548613.jpeg…]()

**Comment by aiwu12** [comment]
> -v模式开启后，看看报错信息是什么
> ![图像](https://user-images.githubusercontent.com/10300651/100193510-e4e2c500-2f2e-11eb-947b-e8129cfa3e19.png)
