### ISSUE TITLE
大佬，这个是-v开启之后，帮忙看下是什么问题

### ISSUE THREAD

**Issue by aiwu12** [839891627/Lenovo_RUI7000_Hackintosh#8]
![82BBB338-B397-4408-A175-6F866F39129C_1_105_c](https://user-images.githubusercontent.com/61082200/100214884-57fa3480-2f4b-11eb-8c5c-02cdff2a98f8.jpeg)

**Comment by 839891627** [comment]
哈？你是怎么替换的？ 只是替换 config.plist ? 还是全部文件？

**Comment by aiwu12** [comment]
全部替换的

**Comment by aiwu12** [comment]
> 是吗？怎么你替换了？只是替换 config.plist?还是全部文件？

全部替换的

**Comment by 839891627** [comment]
https://shuiyunxc.gitee.io/2020/04/06/Faults/index/ 

图15 那个看下

**Comment by 839891627** [comment]
先这上面这个帖子里说的 三个选项置为 true试试。
可能你没解锁

然后给我 star 呀 哈哈哈 右上角
后续再有更新，我会同步的
![image](https://user-images.githubusercontent.com/10300651/100298457-27a6aa80-2fcc-11eb-9905-de29e27b0fc1.png)

**Comment by aiwu12** [comment]
![0A8F42DE-BDDF-4F89-A976-64A26B8C5CBB](https://user-images.githubusercontent.com/61082200/100298675-adc2f100-2fcc-11eb-9ca5-763794e97eeb.jpeg)
这边显示解锁了，也要勾选那几个吗

**Comment by 839891627** [comment]
先试试吧。 这个我没遇到过，不大清楚，也是搜出来别人的

**Comment by aiwu12** [comment]
> 先试试吧。这个我没遇到过，不大清楚，也是搜出来别人的

![3A69EB73-482D-47E1-9933-0574D773AC9A_1_201_a](https://user-images.githubusercontent.com/61082200/100340217-d3281d00-3015-11eb-9496-5ef057c9fa9d.jpeg)
现在跑到这边就重启了

**Comment by 839891627** [comment]
要不去论坛问问吧 😂
